import { Hash } from "crypto";

/** Declaration file generated by dts-gen */

export = keccak;

declare function keccak(algorithm: string, options?: {}): Hash;

declare namespace keccak {
    const prototype: {
    };

}

