/** Declaration file generated by dts-gen */

/* @types/levelupの記述が古くてmemdownが使えないので自前で用意している */

export = levelup

declare class levelup {
  constructor (db: any, options: any, callback: any)

  batch (arr: any, options: any, callback: any, ...args: any[]): any

  close (callback: any, ...args: any[]): any

  createKeyStream (options: any): any

  createReadStream (options: any): any

  createValueStream (options: any): any

  del (key: any, options: any, callback: any): any

  emit (type: any, ...args: any[]): any

  get (key: any, options: any, callback: any): any

  isClosed (): any

  isOpen (): any

  keyStream (options: any): any

  once (type: any, listener: any): any

  open (callback: any): any

  put (key: any, value: any, options: any, callback: any): any

  readStream (options: any): any

  toString (): any

  valueStream (options: any): any

  static default: any
}

declare namespace levelup {
  namespace errors {
    class EncodingError {
      constructor (message: any, cause: any)
    }

    class InitializationError {
      constructor (message: any, cause: any)
    }

    class LevelUPError {
      constructor (message: any, cause: any)
    }

    class NotFoundError {
      constructor (message: any, cause: any)
    }

    class OpenError {
      constructor (message: any, cause: any)
    }

    class ReadError {
      constructor (message: any, cause: any)
    }

    class WriteError {
      constructor (message: any, cause: any)
    }
  }
}
