/** Declaration file generated by dts-gen */

export = memdown;

declare class memdown {
    constructor();

    static default: any;

}

declare namespace memdown {
    namespace prototype {
        function batch(array: any, options: any, callback: any, ...args: any[]): any;

        function close(callback: any): any;

        function del(key: any, options: any, callback: any): any;

        function get(key: any, options: any, callback: any): any;

        function iterator(options: any): any;

        function open(options: any, callback: any): any;

        function put(key: any, value: any, options: any, callback: any): any;

        namespace batch {
            const prototype: {
            };

        }

        namespace close {
            const prototype: {
            };

        }

        namespace del {
            const prototype: {
            };

        }

        namespace get {
            const prototype: {
            };

        }

        namespace iterator {
            const prototype: {
            };

        }

        namespace open {
            const prototype: {
            };

        }

        namespace put {
            const prototype: {
            };

        }

    }

}

